# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False, unique=True, verbose_name='Youtube channel ID')),
                ('name', models.CharField(max_length=100, verbose_name="Channel's name")),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='Youtube video ID')),
                ('title', models.CharField(max_length=100, verbose_name="Video's name")),
                ('date', models.DateTimeField(verbose_name='Publication date')),
                ('channel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.Channel', verbose_name='Channel ID')),
            ],
        ),
    ]
